In [1]:
import pandas as pd
import numpy as np
from utils.utils import clean_up,convert_weekly, holidays

In [2]:
df = pd.read_csv('data/csv/original/sales2023.csv',dtype={'Scan Code':str})
df = clean_up(df)
df

Before removing nan scan codes :  (146274, 15)
After removing NaN scan codes :  (137204, 15)
After removing numm zero costs :  (125560, 13)

SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Date,Scan Code,Description,Department,Qty,POS Cost,POS Retail,Retail at Sale,Selling Units,Margin,Profit,Promo ID,Tran ID,Discounts
0,01/01/2023 9:11:38 AM,078000003154,Dr Pepp CAN,SODA,1.0,0.38,0.92,0.92,1.0,58.70,0.55,0,393456,0.0
1,01/01/2023 9:13:31 AM,810029760997,canna gummy mango,CBD,1.0,8.00,19.99,19.99,1.0,59.98,11.99,0,393457,0.0
2,01/01/2023 9:13:31 AM,6972385041296,uno mango blast,ECigs,1.0,6.40,13.99,13.99,1.0,54.25,7.59,0,393457,0.0
3,01/01/2023 9:13:56 AM,028200003843,MARLBORO GOLD SHORT BOX,MARLBORO,1.0,7.54,7.99,7.99,1.0,5.63,0.45,0,393458,0.0
4,01/01/2023 9:22:40 AM,751667048910,cuban round robusto natural 5*50,IMP CIGAR,3.0,1.24,2.19,2.19,1.0,43.38,2.84,0,393460,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125555,04/20/2023 10:02:32 PM,684746400210,CUB TAIL SUNNY MARGARITA16OZ,BEER,1.0,1.41,2.09,2.09,1.0,32.54,0.68,0,452776,0.0
125556,04/20/2023 10:04:37 PM,6,CAN SODA,SODA,2.0,0.45,0.92,0.92,1.0,51.09,0.94,0,452778,0.0
125557,04/20/2023 10:06:08 PM,684746400210,CUB TAIL SUNNY MARGARITA16OZ,BEER,1.0,1.41,2.09,2.09,1.0,32.54,0.68,0,452779,0.0
125558,04/20/2023 10:08:58 PM,850047695116,Pharma THCA Moon Berry 3.5G,CBD,1.0,23.50,39.99,39.99,1.0,41.24,16.49,0,452780,0.0
125559,04/20/2023 10:08:58 PM,028400436236,MUNCHIES FLAMIN HOT,SNACKS,1.0,1.74,2.49,2.49,1.0,30.12,0.75,0,452780,0.0

In [3]:
weekly_df = convert_weekly(df)
weekly_df

,Date,Scan Code,Description,Department,Qty,POS Cost,POS Retail,Discounts,Month,Week,Year,Avg Temp
0,2023-01-01,008660000026,ZIG-ZAG PAPERS- 1 1/4,Cigar,2.0,1.50,2.790000,0.00,1,52,2023,14.914286
1,2023-01-01,008660000071,ZIG-ZAG PAPERS KING,Cigar,3.0,1.50,2.990000,0.00,1,52,2023,14.914286
2,2023-01-01,008660007384,Zig Zag Hemp 1.25,NOVELTY,2.0,0.87,1.990000,0.00,1,52,2023,14.914286
3,2023-01-01,009060000036,rip rolls blue respberry 1.4oz,CANDY,2.0,0.50,1.690000,0.00,1,52,2023,14.914286
4,2023-01-01,009800000524,KINDER JOY TREAT & TOY,CANDY,3.0,1.67,2.790000,0.00,1,52,2023,14.914286
...,...,...,...,...,...,...,...,...,...,...,...,...
24491,2023-04-16,893919001301,Icelandic Glacial Natural Spring Water - 33.8 ...,NON TAX,2.0,2.03,3.690000,0.00,4,15,2023,20.04
24492,2023-04-16,894135001175,GOOD STUFF P/TOB FULL FLA,TOBACCO,1.0,12.19,16.990000,0.00,4,15,2023,20.04
24493,2023-04-16,895216001046,FOUR LOCO FRUIT PUNCH 24OZ CAN,BEER,2.0,2.53,3.400000,0.19,4,15,2023,20.04
24494,2023-04-16,895216001060,FOUR LOCO PEACH 24OZ CAN,BEER,3.0,2.53,3.526667,0.19,4,15,2023,20.04
24495,2023-04-16,9555755800043,Royal Honey,NOVELTY,7.0,3.50,8.990000,0.00,4,15,2023,20.04

In [5]:
weekly_df = holidays(weekly_df)
weekly_df

,Date,Scan Code,Description,Department,Qty,POS Cost,POS Retail,Discounts,Month,Week,Year,Avg Temp,Holiday
0,2023-01-01,008660000026,ZIG-ZAG PAPERS- 1 1/4,Cigar,2.0,1.50,2.790000,0.00,1,52,2023,14.914286,1
1,2023-01-01,008660000071,ZIG-ZAG PAPERS KING,Cigar,3.0,1.50,2.990000,0.00,1,52,2023,14.914286,1
2,2023-01-01,008660007384,Zig Zag Hemp 1.25,NOVELTY,2.0,0.87,1.990000,0.00,1,52,2023,14.914286,1
3,2023-01-01,009060000036,rip rolls blue respberry 1.4oz,CANDY,2.0,0.50,1.690000,0.00,1,52,2023,14.914286,1
4,2023-01-01,009800000524,KINDER JOY TREAT & TOY,CANDY,3.0,1.67,2.790000,0.00,1,52,2023,14.914286,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24491,2023-04-16,893919001301,Icelandic Glacial Natural Spring Water - 33.8 ...,NON TAX,2.0,2.03,3.690000,0.00,4,15,2023,20.04,2
24492,2023-04-16,894135001175,GOOD STUFF P/TOB FULL FLA,TOBACCO,1.0,12.19,16.990000,0.00,4,15,2023,20.04,2
24493,2023-04-16,895216001046,FOUR LOCO FRUIT PUNCH 24OZ CAN,BEER,2.0,2.53,3.400000,0.19,4,15,2023,20.04,2
24494,2023-04-16,895216001060,FOUR LOCO PEACH 24OZ CAN,BEER,3.0,2.53,3.526667,0.19,4,15,2023,20.04,2
24495,2023-04-16,9555755800043,Royal Honey,NOVELTY,7.0,3.50,8.990000,0.00,4,15,2023,20.04,2